/*
 * Copyright (c) 2022 T-Mobile USA, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */


#ifndef RSI_WLAN_CONFIG_H
#define RSI_WLAN_CONFIG_H


#if CONFIG_WISECONNECT_WIFI

#if CONFIG_WISECONNECT_IP_BYPASS_MODE 
#define RSI_IPBM_BYPASS_CONFIG TCP_IP_FEAT_BYPASS
#else
#define RSI_IPBM_BYPASS_CONFIG 0
#endif

#if CONFIG_WISECONNECT_IP_DUAL_MODE
#define RSI_EIPBM_DM EXT_TCP_IP_DUAL_MODE_ENABLE
#else
#define RSI_EIPBM_DM 0
#endif

#if CONFIG_WISECONNECT_SOCKETS_COUNT
#define RSI_IPBM_SOCKET_CONFIG (CONFIG_WISECONNECT_SOCKETS_COUNT << 21)
#else
#define RSI_IPBM_SOCKET_CONFIG 0
#endif /** CONFIG_WISECONNECT_SOCKETS_COUNT */

#if CONFIG_WISECONNECT_TLS
#define RSI_IPBM_TLS_CONFIG (TCP_IP_FEAT_SSL | TCP_IP_FEAT_LOAD_CERTS_INTO_RAM | TCP_IP_FEAT_LOAD_PUBLIC_PRIVATE_CERTS)
#define RSI_ECFBM_TLS_CONFIG EXT_FEAT_SSL_CERT_WITH_4096_KEY_SUPPORT
// #if CONFIG_WISECONNECT_THREE_TLS_SOCKETS
// #define RSI_EIPBM_TLS3 EXT_TCP_IP_FEAT_SSL_THREE_SOCKETS
// #else
// #define RSI_EIPBM_TLS3 0
// #endif /** CONFIG_WISECONNECT_THREE_TLS_SOCKETS */
#else 
#define RSI_IPBM_TLS_CONFIG 0
#define RSI_ECFBM_TLS_CONFIG 0
#endif /** CONFIG_WISECONNECT_TLS */

#if CONFIG_WISECONNECT_ICMP
#define RSI_IPBM_ICMP_CONFIG TCP_IP_FEAT_ICMP
#else
#define RSI_IPBM_ICMP_CONFIG 0
#endif /** CONFIG_WISECONNECT_ICMP */

#if CONFIG_WISECONNECT_IPV6
#define RSI_IPBM_IPV6_CONFIG TCP_IP_FEAT_IPV6
#else
#define RSI_IPBM_IPV6_CONFIG 0
#endif /** CONFIG_WISECONNECT_IPV6 */

#if CONFIG_WISECONNECT_DHCP
#if CONFIG_WISECONNECT_IPV6
#define RSI_IPBM_DHCP_CONFIG (TCP_IP_FEAT_DHCPV4_CLIENT | TCP_IP_FEAT_DHCPV6_CLIENT)
#else
#define RSI_IPBM_DHCP_CONFIG TCP_IP_FEAT_DHCPV4_CLIENT
#endif
#else
#define RSI_IPBM_DHCP_CONFIG 0
#endif /** CONFIG_WISECONNECT_DHCP */

#if CONFIG_WISECONNECT_DNS
#define RSI_IPBM_DNS_CONFIG TCP_IP_FEAT_DNS_CLIENT
#else
#define RSI_IPBM_DNS_CONFIG 0
#endif

#if CONFIG_WISECONNECT_SOCKETS_LARGE_TRANSACTIONS
#define RSI_PROCESS_MAX_RX_DATA
#endif

#define RSI_TCP_IP_FEATURE_BIT_MAP (RSI_IPBM_SOCKET_CONFIG | \
        RSI_IPBM_TLS_CONFIG | RSI_IPBM_ICMP_CONFIG | RSI_IPBM_IPV6_CONFIG | \
        RSI_IPBM_DHCP_CONFIG | RSI_IPBM_BYPASS_CONFIG | RSI_IPBM_DNS_CONFIG | \
        TCP_IP_FEAT_EXTENSION_VALID)

#define RSI_EXT_TCPIP_FEATURE_BITMAP ((RSI_IPBM_SOCKET_CONFIG >> (21 - 12)) | RSI_EIPBM_DM | \
        EXT_TCP_IP_WAIT_FOR_SOCKET_CLOSE)

#define TCP_RX_WINDOW_SIZE_CAP 20

#define RSI_EXT_CUSTOM_FEATURE_BIT_MAP RSI_ECFBM_TLS_CONFIG

#endif /** CONFIG_WISECONNECT_WIFI */

#include "rsi_wlan_defines.h"
#include "rsi_wlan_common_config.h"
#endif 